In [272]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [273]:
productivity = '~/uniwork/ads/ADS-European-Productivity/Datasets/cleaned_Productivity.csv'
prod_df = pd.read_csv(productivity)
prod_df.drop(['2000', '2001','2002','2003','2004'], axis = 1, inplace =True)

In [274]:
prod_df.drop('mean', axis = 1, inplace = True)
prod_df

,LOCATION,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,AUS,47.099677,47.342066,47.873036,49.523676,49.111719,49.886548,50.465688,51.671243,52.558753,52.780926,54.099648,53.945416,54.561035,54.559641,55.212012,56.214321,56.820351
1,AUT,60.632340,62.218785,63.814049,63.814456,63.363388,64.291488,64.947960,65.645538,66.080679,66.327394,67.267651,67.184974,67.999464,68.309455,68.309868,69.970148,69.634603
2,BEL,67.287921,67.637137,68.887444,68.464336,68.020751,69.053627,68.581978,68.923207,69.517696,70.513657,71.604653,71.674769,71.534022,71.681631,72.259271,74.541737,73.607184
3,BGR,17.965425,18.618248,19.229785,19.475667,19.717737,20.847786,21.781488,22.497211,22.460713,22.607390,23.296069,23.897609,24.130056,24.784139,25.687153,25.775778,26.559335
4,CAN,47.187987,47.742663,47.802103,47.658733,47.877704,48.405298,49.181535,49.335662,50.068609,51.425818,51.340885,51.524774,52.346352,52.543577,52.996192,56.971404,53.969872
5,CHE,64.693828,66.315161,67.595243,68.253612,66.723475,68.620315,68.227615,68.494780,69.759903,70.447419,69.982344,70.431631,71.561236,73.212853,73.619376,74.655861,75.909195
6,CHL,20.756781,21.576242,22.452244,22.983801,23.127019,22.047521,22.524161,23.647491,23.997201,24.412230,24.525405,24.869271,24.794088,25.319539,25.304435,28.606966,28.986876
7,COL,10.232035,10.890402,11.347122,11.360227,11.063533,11.114892,11.496924,11.629282,12.052849,12.371221,12.488134,12.724875,12.862658,13.050577,13.461440,16.115907,14.335103
8,CRI,13.718511,14.259665,14.453706,14.909054,15.331663,17.122775,17.944786,17.694625,18.620355,19.093774,19.707747,20.571849,21.056646,21.446167,22.038536,25.395334,24.023111
9,CZE,32.765277,34.781571,36.256014,36.139167,35.303035,36.128328,36.734795,36.886973,37.004724,37.432375,39.390083,39.251558,40.595969,41.161265,42.272668,43.289836,43.487932
10,DEU,59.900695,60.858653,61.577685,61.593702,59.739676,61.116778,62.706421,63.093299,63.392823,64.049842,64.376152,65.248665,66.411797,66.549287,67.055996,67.714113,68.303361
11,DNK,64.048343,64.892447,65.012119,64.044269,63.453957,65.937261,66.165566,67.430176,67.960405,69.036988,70.022816,70.856515,72.180878,73.769587,74.317394,75.083567,75.831338
12,ESP,45.562108,45.828539,46.335067,46.454358,47.573943,48.783311,49.503478,50.458453,51.203041,51.361566,51.769513,52.006193,52.460584,52.340690,52.631029,52.648278,51.829924
13,EST,28.372540,29.802344,32.051758,30.939920,31.588678,33.280600,32.733169,33.822894,34.255974,35.138109,34.947358,35.864899,36.927656,39.328419,40.593175,42.940260,42.911145
14,FIN,56.779062,58.155532,60.024417,59.322583,56.695101,58.669818,59.482446,58.526417,58.741949,58.857955,59.336748,60.730655,62.263776,61.531074,61.480236,61.675189,61.887283
15,FRA,61.487911,63.018745,62.723395,62.323215,61.685771,62.484285,63.109941,63.316137,64.173601,64.791079,65.316731,65.499243,66.881126,67.155153,67.417144,67.757324,66.745494
16,GBR,55.156626,56.070347,56.864362,56.899648,55.528490,57.078368,57.090117,56.706058,56.978563,57.118628,58.134286,57.918610,58.965284,59.243917,59.515367,60.202901,59.141735
17,GRC,38.332984,39.980723,41.017728,40.454932,39.403018,39.041018,36.286315,34.411592,33.629296,33.419253,34.620568,33.186510,33.648638,32.475541,33.130422,33.996081,33.178190
18,HRV,30.903320,31.427151,31.956235,31.884464,29.803838,30.381448,31.647165,32.356397,33.429929,32.763303,34.335121,35.311994,35.855539,36.214321,35.832518,33.402665,36.361268
19,HUN,31.711223,33.059351,33.880508,34.775614,33.729408,34.161580,35.064454,34.615419,34.885635,34.479125,35.030998,34.239239,35.285256,36.715234,38.245188,38.366856,39.932813
20,IRL,62.593898,62.959165,63.998384,62.217740,65.205840,73.594177,75.548609,76.113393,74.123135,77.947489,94.026554,91.255548,95.445789,99.940868,102.330471,120.281397,128.214179
21,ISL,51.613242,52.938942,56.118409,54.473883,57.958666,57.363205,57.412617,57.495299,58.702973,58.676681,59.662657,60.324542,60.815593,62.370665,64.644798,64.702458,66.026154
22,ISR,35.423816,36.576262,36.977028,36.936883,36.527230,37.589981,38.747445,38.761111,39.681708,40.434969,40.498081,40.841654,41.611018,42.741589,44.129545,46.914607,47.572500
23,ITA,52.990201,52.873541,52.833352,52.532095,51.485627,52.656139,53.011615,52.728249,53.147359,53.189636,53.221214,53.057615,53.399887,53.393274,53.658554,55.284372,54.590990
24,JPN,42.497598,42.564981,42.875805,42.736764,42.149500,43.442626,43.709114,44.189848,45.190245,45.251121,46.162102,46.228687,46.650205,46.892448,47.389768,46.790715,47.283863
25,KOR,25.066255,26.109854,27.762018,29.325932,30.340215,32.147724,33.077795,33.544427,34.297736,35.078734,35.557800,36.548092,38.180621,39.639227,40.575940,41.871053,42.851352
26,LTU,27.812775,30.040743,32.197778,32.957143,31.543369,32.836767,35.093377,35.808682,36.906205,37.617907,37.321514,36.946175,39.684589,40.535723,42.133586,44.685245,46.083657
27,LUX,99.957636,102.035068,104.743364,99.685834,99.484621,101.160094,99.378768,98.989858,100.800784,100.550424,99.777819,101.763319,100.256820,98.578393,97.821744,101.100090,99.030161
28,LVA,23.911079,25.497929,27.534660,27.520156,28.253320,29.176747,29.230218,31.122516,31.138166,31.986784,33.400119,34.281980,35.729988,36.370986,38.032626,39.391199,41.437464
29,MEX,18.773197,19.139057,19.361361,19.244617,18.100579,18.747871,19.079918,19.233563,19.227183,19.713514,19.841226,20.216638,20.329696,20.194667,19.706478,19.615134,18.903278
30,NLD,64.097939,65.051296,65.632495,66.009294,64.520326,65.852731,66.274742,66.176095,66.678971,67.172705,67.832959,67.727181,68.095551,67.876916,67.422659,66.689781,67.704215
31,NOR,82.750646,82.157474,80.742255,78.348249,78.455084,78.789195,78.170009,78.839549,79.340132,79.913585,81.021883,81.489588,83.062125,82.656232,82.030731,83.242597,84.456196
32,NZL,36.908863,37.421156,38.859858,37.664881,39.646401,39.296073,40.052755,41.552746,40.677193,40.618259,41.622831,41.181840,41.238821,42.124762,41.896816,42.493108,43.344340
33,POL,26.725170,27.469543,28.184305,28.402336,29.321396,31.083531,32.549662,33.099257,33.466584,34.050522,34.879786,35.577780,37.315221,39.854227,41.752351,41.230426,41.517137
34,PRT,35.272311,35.927996,36.491637,36.727659,36.569423,37.685603,38.245249,38.619119,39.177467,38.779615,38.771567,38.796107,39.111943,39.075294,39.667314,40.114162,40.508787
35,ROU,18.818376,20.350859,21.467073,23.850073,23.643342,23.160239,24.049819,24.696408,25.927477,26.867369,28.121919,29.395662,31.211224,32.557472,33.576037,32.846876,37.514761
36,RUS,20.051286,21.373371,22.622358,23.700889,22.631987,23.414143,24.058067,24.747730,25.261952,25.331478,24.649304,24.723500,25.137929,25.884473,26.698227,27.680927,28.699798
37,SVK,30.452693,32.274839,34.710747,35.458839,34.443631,36.808876,37.384872,37.942721,38.860596,39.622443,40.990746,41.146460,42.075311,43.157588,44.096386,46.742652,48.091287
38,SVN,36.938074,39.128271,40.808356,40.752803,38.181149,39.491962,40.925467,40.691154,40.292879,40.753894,40.981064,42.404997,44.000646,45.061827,45.540786,45.858710,47.075129
39,SWE,63.473288,65.301313,65.489276,64.336167,63.430047,65.653328,66.185529,65.868736,66.395834,67.152902,69.074511,68.649665,69.261329,69.514519,71.101216,71.857873,73.669232
40,TUR,32.580282,34.111688,35.924232,35.805009,34.328244,35.193220,37.128369,37.905972,40.465033,40.443125,42.094218,43.044787,45.090563,46.227634,47.988606,56.539377,53.129297
41,USA,61.772075,62.356937,63.232583,64.042431,66.089234,67.835887,67.861870,68.118059,68.407849,68.665009,69.047471,69.256659,69.876907,70.664702,71.520554,73.957559,74.838217
42,ZAF,17.469945,18.189686,19.043363,18.446211,18.952649,20.225573,20.299933,20.516167,20.514456,20.533058,22.553865,19.938277,19.927223,19.859829,19.803255,21.265347,22.835387

In [275]:
esi = "~/uniwork/ads/ADS-European-Productivity/Datasets/ESI_Clean.csv"
esi_df = pd.read_csv(esi)
esi_df.columns=esi_df.iloc[0]
esi_df.drop(0, inplace=True) 
geo = esi_df['Month-Year']
esi_df = esi_df.drop('Month-Year', axis = 1)
esi_df = esi_df.astype(np.float64)

esi_df['geo'] = geo
esi_df['2005'] = esi_df.filter(regex='-05').mean(axis=1)
esi_df['2006'] = esi_df.filter(regex='-06').mean(axis=1)
esi_df['2007'] = esi_df.filter(regex='-07').mean(axis=1)
esi_df['2008'] = esi_df.filter(regex='-08').mean(axis=1)
esi_df['2009'] = esi_df.filter(regex='-09').mean(axis=1)
esi_df['2010'] = esi_df.filter(regex='-10').mean(axis=1)
esi_df['2011'] = esi_df.filter(regex='-11').mean(axis=1)
esi_df['2012'] = esi_df.filter(regex='-12').mean(axis=1)
esi_df['2013'] = esi_df.filter(regex='-13').mean(axis=1)
esi_df['2014'] = esi_df.filter(regex='-14').mean(axis=1)
esi_df['2015'] = esi_df.filter(regex='-15').mean(axis=1)
esi_df['2016'] = esi_df.filter(regex='-16').mean(axis=1)
esi_df['2017'] = esi_df.filter(regex='-17').mean(axis=1)
esi_df['2018'] = esi_df.filter(regex='-18').mean(axis=1)
esi_df['2019'] = esi_df.filter(regex='-19').mean(axis=1)
esi_df['2020'] = esi_df.filter(regex='-20').mean(axis=1)
esi_df['2021'] = esi_df.filter(regex='-21').mean(axis=1)

esi_df = esi_df[['geo','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021']]
esi_df.drop([1, 2],axis = 0, inplace=True)

In [276]:

for index, row in esi_df.iterrows():
    if row.geo == 'EL.ESI':
        row.geo = 'GR.ESI'
    if row.geo == 'UK.ESI':
        row.geo = 'GB.ESI'
    
    esi_df.at[index, 'geo'] = pycountry.countries.get(alpha_2 = row.geo[:-4]).alpha_3

In [277]:
esi_df

,geo,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
3,BEL,100.966667,111.616667,112.150000,95.008333,80.416667,102.525000,101.850000,91.033333,94.850000,100.600000,100.675000,102.900000,105.233333,105.533333,97.800000,86.033333,111.150000
4,BGR,107.725000,111.033333,117.575000,114.716667,89.433333,89.883333,92.066667,91.883333,92.166667,95.741667,100.316667,102.741667,106.591667,106.958333,102.550000,82.658333,96.183333
5,CZE,108.166667,113.358333,114.400000,102.775000,80.383333,95.625000,94.516667,87.833333,89.633333,98.725000,103.016667,105.358333,106.741667,107.808333,103.783333,84.958333,94.008333
6,DNK,103.783333,113.016667,105.891667,88.466667,83.983333,108.341667,101.016667,92.725000,97.091667,100.566667,101.708333,101.908333,108.950000,109.366667,102.616667,86.883333,109.908333
7,DEU,93.783333,103.975000,105.808333,92.833333,82.025000,104.333333,107.500000,99.500000,101.625000,103.866667,105.191667,105.533333,110.900000,111.558333,102.475000,91.208333,110.016667
8,EST,111.216667,116.666667,108.391667,87.825000,75.525000,98.083333,102.341667,99.041667,99.425000,98.433333,95.333333,99.375000,105.033333,103.741667,97.966667,86.975000,105.058333
9,GRC,102.241667,108.100000,110.291667,101.166667,87.241667,85.383333,83.458333,83.016667,92.641667,101.016667,91.141667,94.700000,98.150000,102.866667,105.633333,95.475000,106.116667
10,ESP,104.841667,104.125000,103.350000,83.741667,79.866667,89.575000,89.391667,85.858333,90.650000,99.858333,107.750000,106.033333,109.216667,108.025000,104.675000,89.841667,105.116667
11,FRA,101.966667,107.641667,110.800000,93.575000,81.416667,99.016667,100.066667,89.025000,88.133333,91.216667,96.566667,99.616667,107.025000,105.483333,102.491667,89.333333,107.725000
12,CYP,101.708333,103.475000,109.350000,106.533333,91.458333,94.983333,87.766667,81.533333,82.208333,93.525000,99.375000,106.508333,110.841667,111.241667,109.858333,88.925000,99.166667
13,LVA,110.641667,113.833333,111.991667,91.191667,69.916667,92.066667,98.650000,101.250000,101.908333,101.175000,99.025000,101.008333,103.566667,104.108333,102.050000,91.475000,99.125000
14,LTU,108.166667,113.508333,114.341667,96.316667,69.858333,91.016667,99.300000,95.041667,99.766667,98.316667,98.483333,101.191667,104.741667,109.466667,108.616667,96.708333,106.975000
15,LUX,102.200000,105.325000,109.458333,93.483333,85.958333,96.450000,100.816667,87.641667,86.616667,89.916667,93.375000,102.308333,111.516667,109.083333,104.291667,97.083333,113.875000
16,HUN,96.600000,98.891667,94.808333,88.066667,79.616667,96.858333,93.641667,89.058333,97.200000,108.641667,109.433333,107.691667,113.908333,116.541667,110.775000,89.141667,104.333333
17,MLT,93.941667,95.200000,106.783333,100.966667,86.758333,100.925000,95.358333,94.550000,100.258333,105.100000,107.475000,106.841667,112.175000,111.675000,103.041667,82.425000,104.875000
18,NLD,98.416667,111.666667,114.591667,99.083333,80.283333,99.191667,97.641667,89.350000,91.633333,100.150000,103.966667,104.658333,109.100000,109.058333,103.966667,88.691667,106.991667
19,AUT,97.791667,110.241667,110.925000,92.183333,79.966667,100.575000,99.650000,94.650000,96.058333,97.025000,97.641667,101.350000,112.033333,113.000000,103.416667,87.316667,111.916667
20,POL,101.841667,109.675000,119.633333,111.483333,88.541667,101.600000,98.908333,93.525000,92.075000,98.550000,99.950000,102.291667,106.725000,111.900000,107.408333,81.858333,100.975000
21,PRT,98.325000,101.908333,108.350000,99.733333,88.883333,97.533333,88.000000,81.500000,88.725000,100.925000,105.491667,106.766667,112.233333,112.125000,108.708333,87.808333,103.800000
22,ROU,106.033333,109.175000,111.900000,105.691667,79.391667,83.466667,90.733333,92.875000,93.541667,97.958333,102.925000,103.875000,105.983333,102.850000,104.050000,87.900000,99.375000
23,SVN,103.191667,111.450000,111.975000,98.500000,78.733333,94.500000,93.750000,82.900000,87.791667,98.483333,105.191667,105.308333,111.366667,110.441667,106.266667,90.283333,102.483333
24,SVK,106.966667,114.266667,116.525000,100.858333,79.233333,98.066667,97.033333,93.466667,91.266667,100.333333,101.841667,103.875000,105.116667,101.958333,98.758333,86.166667,95.291667
25,FIN,107.150000,111.800000,112.375000,94.541667,83.341667,105.691667,102.075000,93.483333,91.508333,89.808333,91.716667,97.508333,108.541667,108.841667,99.391667,85.591667,109.041667
26,SWE,101.283333,107.858333,109.666667,90.883333,83.458333,108.300000,102.816667,93.500000,95.633333,100.833333,102.483333,104.225000,109.616667,108.066667,98.700000,88.616667,115.025000

In [278]:
#the full dataset doesn't load cause it's too big so this is just general government expenditure as percentage og gdp
gov_exp = '~/uniwork/ads/ADS-European-Productivity/Datasets/gov_exp.csv'
exp_df = pd.read_csv(gov_exp)

In [279]:
exp_df

,DATAFLOW,LAST UPDATE,freq,unit,sector,cofog99,na_item,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG
0,ESTAT:GOV_10A_EXP(1.0),22/02/23 11:00:00,A,PC_GDP,S13,GF01,TE,AT,2005,7.8,NaN
1,ESTAT:GOV_10A_EXP(1.0),22/02/23 11:00:00,A,PC_GDP,S13,GF01,TE,AT,2006,7.7,NaN
2,ESTAT:GOV_10A_EXP(1.0),22/02/23 11:00:00,A,PC_GDP,S13,GF01,TE,AT,2007,7.6,NaN
3,ESTAT:GOV_10A_EXP(1.0),22/02/23 11:00:00,A,PC_GDP,S13,GF01,TE,AT,2008,7.2,NaN
4,ESTAT:GOV_10A_EXP(1.0),22/02/23 11:00:00,A,PC_GDP,S13,GF01,TE,AT,2009,7.8,NaN
...,...,...,...,...,...,...,...,...,...,...,...
40795,ESTAT:GOV_10A_EXP(1.0),22/02/23 11:00:00,A,PC_GDP,S13,TOTAL,TE,SK,2017,39.5,NaN
40796,ESTAT:GOV_10A_EXP(1.0),22/02/23 11:00:00,A,PC_GDP,S13,TOTAL,TE,SK,2018,39.7,NaN
40797,ESTAT:GOV_10A_EXP(1.0),22/02/23 11:00:00,A,PC_GDP,S13,TOTAL,TE,SK,2019,40.5,NaN
40798,ESTAT:GOV_10A_EXP(1.0),22/02/23 11:00:00,A,PC_GDP,S13,TOTAL,TE,SK,2020,44.8,NaN
40799,ESTAT:GOV_10A_EXP(1.0),22/02/23 11:00:00,A,PC_GDP,S13,TOTAL,TE,SK,2021,46.3,NaN

In [280]:
#droping observation fact as there are not that many predited vales and it saves space
exp_df.drop('OBS_FLAG', axis = 1, inplace = True)

In [281]:

sectors = set(exp_df['cofog99'])
countries = set(exp_df['geo'])

In [282]:
#drop irrelevant columns
exp_df.drop('DATAFLOW', axis = 1, inplace = True)
exp_df.drop('LAST UPDATE', axis = 1, inplace = True)
exp_df.drop('unit', axis = 1, inplace = True)
exp_df.drop('sector', axis = 1, inplace = True)

In [283]:
exp_df.drop('freq', axis = 1, inplace = True)
exp_df.drop('na_item', axis = 1, inplace = True)
exp_df.head()

  cofog99 geo  TIME_PERIOD  OBS_VALUE
0    GF01  AT         2005        7.8
1    GF01  AT         2006        7.7
2    GF01  AT         2007        7.6
3    GF01  AT         2008        7.2
4    GF01  AT         2009        7.8

In [284]:
exp_df

      cofog99 geo  TIME_PERIOD  OBS_VALUE
0        GF01  AT         2005        7.8
1        GF01  AT         2006        7.7
2        GF01  AT         2007        7.6
3        GF01  AT         2008        7.2
4        GF01  AT         2009        7.8
...       ...  ..          ...        ...
40795   TOTAL  SK         2017       39.5
40796   TOTAL  SK         2018       39.7
40797   TOTAL  SK         2019       40.5
40798   TOTAL  SK         2020       44.8
40799   TOTAL  SK         2021       46.3

[40800 rows x 4 columns]

In [285]:
exp_df = exp_df[exp_df['cofog99'] != 'TOTAL']
exp_df

      cofog99 geo  TIME_PERIOD  OBS_VALUE
0        GF01  AT         2005        7.8
1        GF01  AT         2006        7.7
2        GF01  AT         2007        7.6
3        GF01  AT         2008        7.2
4        GF01  AT         2009        7.8
...       ...  ..          ...        ...
40285  GF1009  SK         2017        1.4
40286  GF1009  SK         2018        1.3
40287  GF1009  SK         2019        1.2
40288  GF1009  SK         2020        1.3
40289  GF1009  SK         2021        1.2

[40290 rows x 4 columns]

In [286]:
#atempting to get 80 different colours
from matplotlib.colors import hsv_to_rgb

hue_values = np.linspace(0, 1, 80)
ones = np.ones_like(hue_values)
# Convert the hue values to RGB colors using the hsv_to_rgb function

colors = hsv_to_rgb(np.column_stack([hue_values, ones, ones]))

In [287]:
# plot values o for each country
# for country in countries:
#     print(country)
#     fig = plt.figure(figsize=(12, 10))
#     to_plot_df = exp_df[exp_df['geo'] == country]
#     for i, (cofog99, group_df) in enumerate(to_plot_df.groupby('cofog99')):
#         plt.plot(group_df['TIME_PERIOD'], group_df['OBS_VALUE'], color=colors[i], label=cofog99)

#     plt.xlabel('Time Period')
#     plt.ylabel('OBS_VALUE')
#     plt.show()

In [288]:
import seaborn as sns
import matplotlib.pyplot as plt

In [289]:
german_prod = prod_df.iloc[10].values[1:]
german_esi = es_df.iloc[7].values[1:]
german_expenditure = exp_df.loc[exp_df['geo'] == 'DE', 'OBS_VALUE'].values
german_expenditure = np.split(german_expenditure, 79)

In [290]:
import pycountry

In [291]:
#prepare government expenditure dataset so it has teh same country codes as productivity
exp_df_prod = exp_df.copy()
for country in countries:
    
    if country == 'EL':
        exp_df_prod.replace(country, 'GRC', inplace =True)
    else: exp_df_prod.replace(country, pycountry.countries.get(alpha_2=country).alpha_3, inplace =True)

In [292]:
countries = set(exp_df_prod.geo)
countries
# exp_df_prod[exp_df_prod['geo'] =='SVN']

{'AUT',
 'BEL',
 'BGR',
 'CHE',
 'CYP',
 'CZE',
 'DEU',
 'DNK',
 'ESP',
 'EST',
 'FIN',
 'FRA',
 'GRC',
 'HRV',
 'HUN',
 'IRL',
 'ISL',
 'ITA',
 'LTU',
 'LUX',
 'LVA',
 'MLT',
 'NLD',
 'NOR',
 'POL',
 'PRT',
 'ROU',
 'SVK',
 'SVN',
 'SWE'}

In [293]:
exp_df_prod

      cofog99  geo  TIME_PERIOD  OBS_VALUE
0        GF01  AUT         2005        7.8
1        GF01  AUT         2006        7.7
2        GF01  AUT         2007        7.6
3        GF01  AUT         2008        7.2
4        GF01  AUT         2009        7.8
...       ...  ...          ...        ...
40285  GF1009  SVK         2017        1.4
40286  GF1009  SVK         2018        1.3
40287  GF1009  SVK         2019        1.2
40288  GF1009  SVK         2020        1.3
40289  GF1009  SVK         2021        1.2

[40290 rows x 4 columns]

In [294]:
#get rid of teh countries in expenditure but not in productivity
for country in countries:
    if country not in set(prod_df.LOCATION) or country not in set(esi_df.geo):
        exp_df_prod = exp_df_prod[exp_df_prod.geo != country]

In [295]:
#get rid of countries in productivity but not in expenditure
countries = set(prod_df.LOCATION)
for country in countries:
    if country not in set(exp_df_prod.geo) or country not in set(esi_df.geo):
        prod_df = prod_df[prod_df.LOCATION != country]

In [296]:
countries = set(esi_df.geo)
for country in countries:
    if country not in set(prod_df.LOCATION) or country not in set(exp_df_prod.geo):
        esi_df = esi_df[esi_df.geo != country]

In [297]:
countries = set(prod_df.LOCATION)

prod_timeseries = pd.melt(prod_df, id_vars = ['LOCATION'], var_name = 'YEAR', value_name= 'PRODUCTIVITY').sort_values('LOCATION')
prod_timeseries

    LOCATION  YEAR  PRODUCTIVITY
0        AUT  2005     60.632340
198      AUT  2014     66.327394
154      AUT  2012     65.645538
220      AUT  2015     67.267651
132      AUT  2011     64.947960
..       ...   ...           ...
65       SWE  2007     65.489276
307      SWE  2018     69.514519
43       SWE  2006     65.301313
241      SWE  2015     69.074511
373      SWE  2021     73.669232

[374 rows x 3 columns]

In [301]:
esi_timeseries = pd.melt(esi_df, id_vars = ['geo'], var_name = 'YEAR', value_name= 'ESI').sort_values('geo')

In [298]:
cofog99 = set(exp_df_prod.cofog99)
cofog99

{'GF01',
 'GF0101',
 'GF0102',
 'GF0103',
 'GF0104',
 'GF0105',
 'GF0106',
 'GF0107',
 'GF0108',
 'GF02',
 'GF0201',
 'GF0202',
 'GF0203',
 'GF0204',
 'GF0205',
 'GF03',
 'GF0301',
 'GF0302',
 'GF0303',
 'GF0304',
 'GF0305',
 'GF0306',
 'GF04',
 'GF0401',
 'GF0402',
 'GF0403',
 'GF0404',
 'GF0405',
 'GF0406',
 'GF0407',
 'GF0408',
 'GF0409',
 'GF05',
 'GF0501',
 'GF0502',
 'GF0503',
 'GF0504',
 'GF0505',
 'GF0506',
 'GF06',
 'GF0601',
 'GF0602',
 'GF0603',
 'GF0604',
 'GF0605',
 'GF0606',
 'GF07',
 'GF0701',
 'GF0702',
 'GF0703',
 'GF0704',
 'GF0705',
 'GF0706',
 'GF08',
 'GF0801',
 'GF0802',
 'GF0803',
 'GF0804',
 'GF0805',
 'GF0806',
 'GF09',
 'GF0901',
 'GF0902',
 'GF0903',
 'GF0904',
 'GF0905',
 'GF0906',
 'GF0907',
 'GF0908',
 'GF10',
 'GF1001',
 'GF1002',
 'GF1003',
 'GF1004',
 'GF1005',
 'GF1006',
 'GF1007',
 'GF1008',
 'GF1009'}

In [302]:
esi_timeseries.head

<bound method NDFrame.head of      geo  YEAR         ESI
366  AUT  2021  111.916667
124  AUT  2010  100.575000
278  AUT  2017  112.033333
14   AUT  2005   97.791667
168  AUT  2012   94.650000
..   ...   ...         ...
65   SWE  2007  109.666667
153  SWE  2011  102.816667
43   SWE  2006  107.858333
131  SWE  2010  108.300000
373  SWE  2021  115.025000

[374 rows x 3 columns]>

In [303]:
prod_timeseries.head

<bound method NDFrame.head of     LOCATION  YEAR  PRODUCTIVITY
0        AUT  2005     60.632340
198      AUT  2014     66.327394
154      AUT  2012     65.645538
220      AUT  2015     67.267651
132      AUT  2011     64.947960
..       ...   ...           ...
65       SWE  2007     65.489276
307      SWE  2018     69.514519
43       SWE  2006     65.301313
241      SWE  2015     69.074511
373      SWE  2021     73.669232

[374 rows x 3 columns]>

In [304]:
exp_df_prod.head

<bound method NDFrame.head of       cofog99  geo  TIME_PERIOD  OBS_VALUE
0        GF01  AUT         2005        7.8
1        GF01  AUT         2006        7.7
2        GF01  AUT         2007        7.6
3        GF01  AUT         2008        7.2
4        GF01  AUT         2009        7.8
...       ...  ...          ...        ...
40285  GF1009  SVK         2017        1.4
40286  GF1009  SVK         2018        1.3
40287  GF1009  SVK         2019        1.2
40288  GF1009  SVK         2020        1.3
40289  GF1009  SVK         2021        1.2

[29546 rows x 4 columns]>

In [321]:
for i in cofog99:
    data = exp_df_prod[exp_df_prod.cofog99 == i]
    data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
    data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
    print(i)
    print("Correlation with productivity:")
    print(data[['prod', 'OBS_VALUE']].corr())
    print("Correlation with ESI:")
    print(data[['esi', 'OBS_VALUE']].corr())

/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

GF08
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.017703
OBS_VALUE  0.017703   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.058064
OBS_VALUE -0.058064   1.000000
GF0505
Correlation with productivity:
              prod  OBS_VALUE
prod       1.00000   -0.04053
OBS_VALUE -0.04053    1.00000
Correlation with ESI:
               esi  OBS_VALUE
esi        1.00000   -0.05519
OBS_VALUE -0.05519    1.00000
GF0803
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.155771
OBS_VALUE  0.155771   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.007768
OBS_VALUE -0.007768   1.000000
GF10
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.365964
OBS_VALUE  0.365964   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.021571
OBS_VALUE  0.021571   1.000000
GF0106
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.145941
OBS_VALUE  0.145941   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.033278
OBS_VALUE  0.033278   1.000000
GF0907
Correlation with productivity:
              prod  OBS_VALUE
prod       1.00000   -0.25038
OBS_VALUE -0.25038    1.00000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.005009
OBS_VALUE  0.005009   1.000000
GF0205
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.168156
OBS_VALUE -0.168156   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.027968
OBS_VALUE -0.027968   1.000000
GF0104
Correlation with productivity:
              prod  OBS_VALUE
prod       1.00000    0.35271
OBS_VALUE  0.35271    1.00000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.029664
OBS_VALUE  0.029664   1.000000
GF0302
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.294053
OBS_VALUE -0.294053   1.000000
Correlation with ESI:
               esi  OBS_VALUE
esi        1.00000   -0.05637
OBS_VALUE -0.05637    1.00000
GF1008
Correlation with productivity:
           prod  OBS_VALUE
prod        1.0        NaN
OBS_VALUE   NaN        NaN
Correlation with ESI:
           esi  OBS_VALUE
esi        1.0        NaN
OBS_VALUE  NaN        NaN
GF0402
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.399415
OBS_VALUE -0.399415   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.020355
OBS_VALUE -0.020355   1.000000
GF0506
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.132322
OBS_VALUE -0.132322   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.000688
OBS_VALUE  0.000688   1.000000
GF1007
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.384305
OBS_VALUE  0.384305   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.000369
OBS_VALUE  0.000369   1.000000
GF0107
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.133746
OBS_VALUE -0.133746   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.023771
OBS_VALUE  0.023771   1.000000
GF0502
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.059211
OBS_VALUE  0.059211   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.010629
OBS_VALUE -0.010629   1.000000
GF0605
Correlation with productivity:
           prod  OBS_VALUE
prod        1.0        NaN
OBS_VALUE   NaN        NaN
Correlation with ESI:
           esi  OBS_VALUE
esi        1.0        NaN
OBS_VALUE  NaN        NaN
GF0802
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.140169
OBS_VALUE -0.140169   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.049026
OBS_VALUE -0.049026   1.000000
GF0403
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.241868
OBS_VALUE -0.241868   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.004693
OBS_VALUE  0.004693   1.000000
GF1003
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.081372
OBS_VALUE -0.081372   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.026762
OBS_VALUE  0.026762   1.000000
GF0301
Correlation with productivity:
              prod  OBS_VALUE
prod       1.00000   -0.54083
OBS_VALUE -0.54083    1.00000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.043763
OBS_VALUE -0.043763   1.000000
GF05
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.066714
OBS_VALUE  0.066714   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.047748
OBS_VALUE -0.047748   1.000000
GF0404
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.209093
OBS_VALUE -0.209093   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.047857
OBS_VALUE  0.047857   1.000000
GF0701
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.331298
OBS_VALUE  0.331298   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.016974
OBS_VALUE -0.016974   1.000000
GF0102
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.464454
OBS_VALUE  0.464454   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.014581
OBS_VALUE -0.014581   1.000000
GF1005
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.454397
OBS_VALUE  0.454397   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.005625
OBS_VALUE  0.005625   1.000000
GF06
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.478145
OBS_VALUE -0.478145   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.020851
OBS_VALUE -0.020851   1.000000
GF0602
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.062571
OBS_VALUE -0.062571   1.000000
Correlation with ESI:
             esi  OBS_VALUE
esi        1.000     -0.048
OBS_VALUE -0.048      1.000
GF1002
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.020019
OBS_VALUE -0.020019   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.000787
OBS_VALUE  0.000787   1.000000
GF0501
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.166101
OBS_VALUE -0.166101   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.004716
OBS_VALUE -0.004716   1.000000
GF0702
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.235412
OBS_VALUE  0.235412   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.001335
OBS_VALUE  0.001335   1.000000
GF0606
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.411521
OBS_VALUE -0.411521   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.016489
OBS_VALUE  0.016489   1.000000
GF0904
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.066485
OBS_VALUE -0.066485   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.018702
OBS_VALUE -0.018702   1.000000
GF0906
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.140668
OBS_VALUE  0.140668   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.001836
OBS_VALUE -0.001836   1.000000
GF1006
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.019128
OBS_VALUE  0.019128   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.013489
OBS_VALUE -0.013489   1.000000
GF0901
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.109644
OBS_VALUE  0.109644   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.003748
OBS_VALUE  0.003748   1.000000
GF09
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.110298
OBS_VALUE  0.110298   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.024812
OBS_VALUE -0.024812   1.000000
GF0303
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.531981
OBS_VALUE -0.531981   1.000000
Correlation with ESI:
               esi  OBS_VALUE
esi        1.00000    0.02132
OBS_VALUE  0.02132    1.00000
GF0604
Correlation with productivity:
             prod  OBS_VALUE
prod       1.0000    -0.4703
OBS_VALUE -0.4703     1.0000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.010874
OBS_VALUE -0.010874   1.000000
GF0705
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.392113
OBS_VALUE  0.392113   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.018798
OBS_VALUE  0.018798   1.000000
GF0801
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.111962
OBS_VALUE  0.111962   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.054934
OBS_VALUE -0.054934   1.000000
GF0405
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.081644
OBS_VALUE -0.081644   1.000000
Correlation with ESI:

/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

                esi  OBS_VALUE
esi        1.000000  -0.016535
OBS_VALUE -0.016535   1.000000
GF0706
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.063396
OBS_VALUE -0.063396   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.008278
OBS_VALUE -0.008278   1.000000
GF02
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.517313
OBS_VALUE -0.517313   1.000000
Correlation with ESI:
               esi  OBS_VALUE
esi        1.00000   -0.00416
OBS_VALUE -0.00416    1.00000
GF0407
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.084915
OBS_VALUE  0.084915   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.089011
OBS_VALUE -0.089011   1.000000
GF0406
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.018217
OBS_VALUE  0.018217   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.077138
OBS_VALUE -0.077138   1.000000
GF0603
Correlation with productivity:
              prod  OBS_VALUE
prod       1.00000   -0.44288
OBS_VALUE -0.44288    1.00000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.088484
OBS_VALUE -0.088484   1.000000
GF0408
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.327968
OBS_VALUE  0.327968   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.067753
OBS_VALUE -0.067753   1.000000
GF0105
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.370384
OBS_VALUE -0.370384   1.000000
Correlation with ESI:
               esi  OBS_VALUE
esi        1.00000   -0.03508
OBS_VALUE -0.03508    1.00000
GF0305
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.083007
OBS_VALUE -0.083007   1.000000
Correlation with ESI:
               esi  OBS_VALUE
esi        1.00000   -0.05614
OBS_VALUE -0.05614    1.00000
GF04
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.158534
OBS_VALUE -0.158534   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.003177
OBS_VALUE -0.003177   1.000000
GF0103
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.180142
OBS_VALUE  0.180142   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.040861
OBS_VALUE -0.040861   1.000000
GF01
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.046027
OBS_VALUE  0.046027   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.004255
OBS_VALUE -0.004255   1.000000
GF0704
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.110787
OBS_VALUE -0.110787   1.000000
Correlation with ESI:
               esi  OBS_VALUE
esi        1.00000    0.03817
OBS_VALUE  0.03817    1.00000
GF1001
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.360498
OBS_VALUE  0.360498   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.048265
OBS_VALUE  0.048265   1.000000
GF0804
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.231231
OBS_VALUE  0.231231   1.000000
Correlation with ESI:
               esi  OBS_VALUE
esi        1.00000    0.01425
OBS_VALUE  0.01425    1.00000
GF0905
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.149533
OBS_VALUE  0.149533   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.037072
OBS_VALUE  0.037072   1.000000
GF1004
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.465007
OBS_VALUE  0.465007   1.000000
Correlation with ESI:
               esi  OBS_VALUE
esi        1.00000    0.00982
OBS_VALUE  0.00982    1.00000
GF0203
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.123049
OBS_VALUE  0.123049   1.000000
Correlation with ESI:
               esi  OBS_VALUE
esi        1.00000    0.03983
OBS_VALUE  0.03983    1.00000
GF0409
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.314263
OBS_VALUE -0.314263   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.046433
OBS_VALUE  0.046433   1.000000
GF0703
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.197693
OBS_VALUE  0.197693   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.019705
OBS_VALUE  0.019705   1.000000
GF0108
Correlation with productivity:
             prod  OBS_VALUE
prod       1.0000     0.1105
OBS_VALUE  0.1105     1.0000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.072303
OBS_VALUE  0.072303   1.000000
GF0401
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.012511
OBS_VALUE  0.012511   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.019198
OBS_VALUE  0.019198   1.000000
GF0504
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.173818
OBS_VALUE  0.173818   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.094869
OBS_VALUE -0.094869   1.000000
GF0806
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.362337
OBS_VALUE -0.362337   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.068707
OBS_VALUE -0.068707   1.000000
GF0201
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.491925
OBS_VALUE -0.491925   1.000000
Correlation with ESI:
               esi  OBS_VALUE
esi        1.00000   -0.00147
OBS_VALUE -0.00147    1.00000
GF0204
Correlation with productivity:
              prod  OBS_VALUE
prod       1.00000   -0.18929
OBS_VALUE -0.18929    1.00000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.068903
OBS_VALUE -0.068903   1.000000
GF0902
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.145774
OBS_VALUE  0.145774   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.031638
OBS_VALUE -0.031638   1.000000
GF0805
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.080975
OBS_VALUE -0.080975   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.048266
OBS_VALUE -0.048266   1.000000
GF0903
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.050477
OBS_VALUE  0.050477   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.023292
OBS_VALUE -0.023292   1.000000
GF0306
Correlation with productivity:
              prod  OBS_VALUE
prod       1.00000   -0.00976
OBS_VALUE -0.00976    1.00000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.037659
OBS_VALUE  0.037659   1.000000
GF03
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.552217
OBS_VALUE -0.552217   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.044721
OBS_VALUE -0.044721   1.000000
GF0101
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.362243
OBS_VALUE -0.362243   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.013071
OBS_VALUE -0.013071   1.000000
GF0202
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.116601
OBS_VALUE -0.116601   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.007324
OBS_VALUE -0.007324   1.000000
GF0304
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.017259
OBS_VALUE -0.017259   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.031371
OBS_VALUE -0.031371   1.000000
GF07
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.374521
OBS_VALUE  0.374521   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.017837
OBS_VALUE  0.017837   1.000000
GF0503
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.135531
OBS_VALUE  0.135531   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.059652
OBS_VALUE -0.059652   1.000000
GF0908
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.415904
OBS_VALUE -0.415904   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.072875
OBS_VALUE -0.072875   1.000000
GF0601
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.157589
OBS_VALUE -0.157589   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.018479
OBS_VALUE  0.018479   1.000000
GF1009
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.182364
OBS_VALUE  0.182364   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.014226
OBS_VALUE  0.014226   1.000000

/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)

In [299]:
#correlation between government expenditure and productivity in germany
german_prod = german_prod.astype('float64')
j = 0
for i in german_expenditure:
    # print(i.dtype)
    print(list(sectors)[j])
    j+=1
    print(np.corrcoef(i, german_prod))

GF08
[[ 1.         -0.65784641]
 [-0.65784641  1.        ]]
GF0505
[[1.         0.81059526]
 [0.81059526 1.        ]]
GF0803
[[1.         0.90814876]
 [0.90814876 1.        ]]
GF10
[[1.        0.8580432]
 [0.8580432 1.       ]]
GF0106
[[1.         0.80265179]
 [0.80265179 1.        ]]
GF0907
[[nan nan]
 [nan  1.]]
GF0205
[[1.         0.36991713]
 [0.36991713 1.        ]]
GF0104
[[ 1.         -0.97424613]
 [-0.97424613  1.        ]]
GF0302
[[nan nan]
 [nan  1.]]
GF1008
[[1.         0.59021609]
 [0.59021609 1.        ]]
GF0402
[[1.         0.49595211]
 [0.49595211 1.        ]]
GF0506
[[nan nan]
 [nan  1.]]
GF1007
[[1.         0.72513942]
 [0.72513942 1.        ]]
GF0107
[[nan nan]
 [nan  1.]]
GF0502
[[nan nan]
 [nan  1.]]
GF0605
[[1.         0.50415944]
 [0.50415944 1.        ]]
GF0802
[[1.         0.39979028]
 [0.39979028 1.        ]]
GF0403
[[1.         0.75697087]
 [0.75697087 1.        ]]
GF1003
[[nan nan]
 [nan  1.]]
GF0301
[[nan nan]
 [nan  1.]]
GF05
[[nan nan]
 [nan  1.]]
GF0404
[[nan nan]
 [nan  1.]]
GF0701
[[1.         0.11822814]
 [0.11822814 1.        ]]
GF0102
[[1.         0.01620002]
 [0.01620002 1.        ]]
GF1005
[[nan nan]
 [nan  1.]]
GF06
[[1.         0.19615834]
 [0.19615834 1.        ]]
GF0602
[[ 1.         -0.67143103]
 [-0.67143103  1.        ]]
GF1002
[[1.         0.40023935]
 [0.40023935 1.        ]]
GF0501
[[nan nan]
 [nan  1.]]
GF0702
[[1.         0.58041871]
 [0.58041871 1.        ]]
GF0606
[[1.         0.82158774]
 [0.82158774 1.        ]]
GF0904
[[1.         0.04526469]
 [0.04526469 1.        ]]
GF0906
[[1.         0.26215662]
 [0.26215662 1.        ]]
GF1006
[[nan nan]
 [nan  1.]]
GF0901
[[ 1.         -0.72513942]
 [-0.72513942  1.        ]]
GF09
[[1.         0.65914708]
 [0.65914708 1.        ]]
GF0303
[[1.         0.68099043]
 [0.68099043 1.        ]]
GF0604
[[nan nan]
 [nan  1.]]
GF0705
[[ 1.         -0.35854367]
 [-0.35854367  1.        ]]
GF0801
[[ 1.         -0.73601648]
 [-0.73601648  1.        ]]
GF0405
[[ 1.         -0.75780896]
 [-0.75780896  1.        ]]
GF0706
[[nan nan]
 [nan  1.]]
GF02
[[nan nan]
 [nan  1.]]
GF0407
[[nan nan]
 [nan  1.]]
GF0406
[[nan nan]
 [nan  1.]]
GF0603
[[nan nan]
 [nan  1.]]
GF0408
[[1.         0.78567191]
 [0.78567191 1.        ]]
GF0105
[[1.         0.65585061]
 [0.65585061 1.        ]]
GF0305
[[1.         0.83521186]
 [0.83521186 1.        ]]
GF04
[[1.         0.58140826]
 [0.58140826 1.        ]]
GF0103
[[1.         0.70464638]
 [0.70464638 1.        ]]
GF01
[[nan nan]
 [nan  1.]]
TOTAL
[[1.         0.61702997]
 [0.61702997 1.        ]]
GF0704
[[ 1.         -0.55441115]
 [-0.55441115  1.        ]]
GF1001
[[ 1.         -0.28376263]
 [-0.28376263  1.        ]]
GF0804
[[1.         0.36991713]
 [0.36991713 1.        ]]
GF0905
[[ 1.         -0.61803477]
 [-0.61803477  1.        ]]
GF1004
[[nan nan]
 [nan  1.]]
GF0203
[[1.        0.3672691]
 [0.3672691 1.       ]]
GF0409
[[nan nan]
 [nan  1.]]
GF0703
[[1.         0.58487266]
 [0.58487266 1.        ]]
GF0108
[[1.         0.88115284]
 [0.88115284 1.        ]]
GF0401
[[ 1.         -0.75314537]
 [-0.75314537  1.        ]]
GF0504
[[nan nan]
 [nan  1.]]
GF0806
[[ 1.        -0.3257716]
 [-0.3257716  1.       ]]
GF0201
[[nan nan]
 [nan  1.]]
GF0204
[[1.         0.34981861]
 [0.34981861 1.        ]]
GF0902
[[nan nan]
 [nan  1.]]
GF0805
[[ 1.         -0.16210053]
 [-0.16210053  1.        ]]
GF0903
[[1.         0.13540044]
 [0.13540044 1.        ]]
GF0306
[[1.         0.85040565]
 [0.85040565 1.        ]]
GF03
[[1.         0.18945141]
 [0.18945141 1.        ]]
GF0101
[[ 1.         -0.44668388]
 [-0.44668388  1.        ]]
GF0202
[[1.         0.74875469]
 [0.74875469 1.        ]]
GF0304
[[ 1.         -0.73818525]
 [-0.73818525  1.        ]]
GF07
[[ 1.         -0.81097821]
 [-0.81097821  1.        ]]
GF0503
[[1.         0.79528219]
 [0.79528219 1.        ]]
GF0908
[[nan nan]
 [nan  1.]]
GF0601
[[ 1.        -0.6117061]
 [-0.6117061  1.       ]]

/home/andreea/miniforge3/envs/uni/lib/python3.11/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/andreea/miniforge3/envs/uni/lib/python3.11/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

In [300]:
#correlation between esi and general government expenditure in germany
german_esi = german_esi.astype('float64')
j = 0
for i in german_expenditure:
    # print(i.dtype)
    print(list(sectors)[j])
    j+=1
    print(np.corrcoef(i, german_esi))

GF08
[[ 1.         -0.25684333]
 [-0.25684333  1.        ]]
GF0505
[[ 1.         -0.05015437]
 [-0.05015437  1.        ]]
GF0803
[[ 1.        -0.0060638]
 [-0.0060638  1.       ]]
GF10
[[ 1.         -0.06650896]
 [-0.06650896  1.        ]]
GF0106
[[ 1.         -0.11328192]
 [-0.11328192  1.        ]]
GF0907
[[nan nan]
 [nan  1.]]
GF0205
[[ 1.         -0.06600237]
 [-0.06600237  1.        ]]
GF0104
[[ 1.         -0.06815167]
 [-0.06815167  1.        ]]
GF0302
[[nan nan]
 [nan  1.]]
GF1008
[[1.         0.27357299]
 [0.27357299 1.        ]]
GF0402
[[1.         0.26041691]
 [0.26041691 1.        ]]
GF0506
[[nan nan]
 [nan  1.]]
GF1007
[[1.         0.09721454]
 [0.09721454 1.        ]]
GF0107
[[nan nan]
 [nan  1.]]
GF0502
[[nan nan]
 [nan  1.]]
GF0605
[[1.         0.18463417]
 [0.18463417 1.        ]]
GF0802
[[1.         0.15770107]
 [0.15770107 1.        ]]
GF0403
[[1.         0.04280491]
 [0.04280491 1.        ]]
GF1003
[[nan nan]
 [nan  1.]]
GF0301
[[nan nan]
 [nan  1.]]
GF05
[[nan nan]
 [nan  1.]]
GF0404
[[nan nan]
 [nan  1.]]
GF0701
[[1.         0.11650667]
 [0.11650667 1.        ]]
GF0102
[[1.         0.12582144]
 [0.12582144 1.        ]]
GF1005
[[nan nan]
 [nan  1.]]
GF06
[[1.         0.32148505]
 [0.32148505 1.        ]]
GF0602
[[ 1.         -0.10297845]
 [-0.10297845  1.        ]]
GF1002
[[1.        0.0808523]
 [0.0808523 1.       ]]
GF0501
[[nan nan]
 [nan  1.]]
GF0702
[[1.         0.08959045]
 [0.08959045 1.        ]]
GF0606
[[ 1.         -0.00659283]
 [-0.00659283  1.        ]]
GF0904
[[ 1.         -0.41489477]
 [-0.41489477  1.        ]]
GF0906
[[1.         0.26061749]
 [0.26061749 1.        ]]
GF1006
[[nan nan]
 [nan  1.]]
GF0901
[[ 1.         -0.09721454]
 [-0.09721454  1.        ]]
GF09
[[1.         0.02414636]
 [0.02414636 1.        ]]
GF0303
[[1.         0.01570184]
 [0.01570184 1.        ]]
GF0604
[[nan nan]
 [nan  1.]]
GF0705
[[1.         0.40732083]
 [0.40732083 1.        ]]
GF0801
[[1.         0.22134893]
 [0.22134893 1.        ]]
GF0405
[[1.         0.15047099]
 [0.15047099 1.        ]]
GF0706
[[nan nan]
 [nan  1.]]
GF02
[[nan nan]
 [nan  1.]]
GF0407
[[nan nan]
 [nan  1.]]
GF0406
[[nan nan]
 [nan  1.]]
GF0603
[[nan nan]
 [nan  1.]]
GF0408
[[1.         0.03448418]
 [0.03448418 1.        ]]
GF0105
[[1.         0.00993907]
 [0.00993907 1.        ]]
GF0305
[[ 1.        -0.0366459]
 [-0.0366459  1.       ]]
GF04
[[1.         0.10746938]
 [0.10746938 1.        ]]
GF0103
[[1.         0.15965022]
 [0.15965022 1.        ]]
GF01
[[nan nan]
 [nan  1.]]
TOTAL
[[1.         0.10052163]
 [0.10052163 1.        ]]
GF0704
[[ 1.         -0.12606876]
 [-0.12606876  1.        ]]
GF1001
[[ 1.         -0.15451257]
 [-0.15451257  1.        ]]
GF0804
[[ 1.         -0.06600237]
 [-0.06600237  1.        ]]
GF0905
[[1.         0.34195114]
 [0.34195114 1.        ]]
GF1004
[[nan nan]
 [nan  1.]]
GF0203
[[ 1.         -0.04947665]
 [-0.04947665  1.        ]]
GF0409
[[nan nan]
 [nan  1.]]
GF0703
[[1.        0.1113525]
 [0.1113525 1.       ]]
GF0108
[[1.         0.13936573]
 [0.13936573 1.        ]]
GF0401
[[1.         0.03597743]
 [0.03597743 1.        ]]
GF0504
[[nan nan]
 [nan  1.]]
GF0806
[[ 1.         -0.17723913]
 [-0.17723913  1.        ]]
GF0201
[[nan nan]
 [nan  1.]]
GF0204
[[ 1.         -0.08508201]
 [-0.08508201  1.        ]]
GF0902
[[nan nan]
 [nan  1.]]
GF0805
[[ 1.         -0.01898809]
 [-0.01898809  1.        ]]
GF0903
[[1.         0.31897252]
 [0.31897252 1.        ]]
GF0306
[[ 1.         -0.00433658]
 [-0.00433658  1.        ]]
GF03
[[1.         0.24195796]
 [0.24195796 1.        ]]
GF0101
[[1.         0.36921838]
 [0.36921838 1.        ]]
GF0202
[[1.         0.01754984]
 [0.01754984 1.        ]]
GF0304
[[1.         0.23987321]
 [0.23987321 1.        ]]
GF07
[[1.         0.13419061]
 [0.13419061 1.        ]]
GF0503
[[1.         0.26099561]
 [0.26099561 1.        ]]
GF0908
[[nan nan]
 [nan  1.]]
GF0601
[[ 1.         -0.07040789]
 [-0.07040789  1.        ]]